### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'freetype'

### ISSUE THREAD

**Issue by joseluislo12** [kkoomen/qbr#24] opened 2021-09-20 14:07 UTC
I'm trying to execute the program but after run `./src/qbr.py` I get

`Traceback (most recent call last):
  File "./src/qbr.py", line 82, in <module>
    Qbr(args.normalize).run()
  File "./src/qbr.py", line 38, in run
    state = webcam.run()
  File "/.../qbr/src/video.py", line 504, in run
    self.draw_current_language(frame)
  File "/.../qbr/src/video.py", line 343, in draw_current_language
    (textsize_width, textsize_height), _ = self.get_text_size(text)
  File "/.../qbr/src/video.py", line 276, in get_text_size
    ft2 = self.get_freetype2_font()
  File "/.../qbr/src/video.py", line 263, in get_freetype2_font
    ft2 = cv2.freetype.createFreeType2()
AttributeError: module 'cv2.cv2' has no attribute 'freetype'`

I'm using Debian 10 as a Virtual Machine (VirtualBox)

**Comment by kkoomen** [comment] 2021-09-21 19:16
Duplicate of #21

**Closed by kkoomen** 2021-09-21 19:16 UTC

**Comment by kkoomen** [comment] 2022-11-05 15:42
Hi. I just released a new version which uses pillow to draw the text and have completely removed the opencv-contrib-python dependency. Reinstall the dependencies with `pip3 install -r requirements.txt` and then run `./src/qbr.py` should be working without the error that `freetype` doesn't exists.
