### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'freetype'`

### ISSUE THREAD

**Issue by AhmedDawoud3** [kkoomen/qbr#20] opened 2021-05-21 10:55 UTC
Windows 
```
Traceback (most recent call last):
  File "k:\Project\qbr\src\qbr.py", line 83, in <module>
    Qbr(args.normalize).run()
  File "k:\Project\qbr\src\qbr.py", line 39, in run
    state = webcam.run()
  File "k:\Project\qbr\src\video.py", line 504, in run
    self.draw_current_language(frame)
  File "k:\Project\qbr\src\video.py", line 343, in draw_current_language
    (textsize_width, textsize_height), _ = self.get_text_size(text)
  File "k:\Project\qbr\src\video.py", line 276, in get_text_size
    ft2 = self.get_freetype2_font()
  File "k:\Project\qbr\src\video.py", line 263, in get_freetype2_font
    ft2 = cv2.freetype.createFreeType2()
AttributeError: module 'cv2.cv2' has no attribute 'freetype'
```

**Comment by kkoomen** [comment] 2021-05-21 14:37
Duplicate of #14

**Closed by kkoomen** 2021-05-21 14:37 UTC

**Comment by kkoomen** [comment] 2022-11-05 15:42
Hi. I just released a new version which uses pillow to draw the text and have completely removed the opencv-contrib-python dependency. Reinstall the dependencies with `pip3 install -r requirements.txt` and then run `./src/qbr.py` should be working without the error that `freetype` doesn't exists.
